version: "3"
services:
  performance-bot:
    image: squatteam/performance-bot:latest
    ports:
      - "8080"
  modifiability-bot:
    image: squatteam/modifiability-bot:latest
    ports:
      - "8081"
  negotiator:
    image: squatteam/negotiator:latest
    ports:
      - "8080"
      - "8081"
      - "8082:8082"
    depends_on:
      - performance-bot
      - modifiability-bot