version: "3"
services:
  performance-bot:
    image: squatteam/performance-bot:latest
    ports:
      - "8080:8080"
  negotiator:
    image: squatteam/negotiator:latest
    ports:
      - "8080:8080"
      - "8081:8081"
  modifiability-bot:
    image: squatteam/modifiability-bot:latest
    ports:
      - "8081:8081"