version: "2"
services:
  performance-bot-1:
    image: squatteam/performance-bot:latest
    ports:
      - "8080"
  performance-bot-2:
    image: squatteam/performance-bot:latest
    ports:
      - "8080"
  performance-bot-3:
    image: squatteam/performance-bot:latest
    ports:
      - "8080"
  performance-bot-4:
    image: squatteam/performance-bot:latest
    ports:
      - "8080"
  modifiability-bot-1:
    image: squatteam/modifiability-bot:latest
    ports:
      - "8081"
  modifiability-bot-2:
    image: squatteam/modifiability-bot:latest
    ports:
      - "8081"
  modifiability-bot-3:
    image: squatteam/modifiability-bot:latest
    ports:
      - "8081"
  modifiability-bot-4:
    image: squatteam/modifiability-bot:latest
    ports:
      - "8081"
  negotiator:
    image: squatteam/negotiator:latest
    ports:
      - "8082:8082"
    depends_on:
      - performance-bot-1
      - performance-bot-2
      - performance-bot-3
      - performance-bot-4
      - modifiability-bot-1
      - modifiability-bot-2
      - modifiability-bot-3
      - modifiability-bot-4
