package io.github.squat_team.modifiability;

public enum ModifiabilityElement {
	COMPONENT, INTERFACE, 
	DATATYPE, SIGNATURE, OPERATION, PARAMETER, 
	REQUIREDROLE, PROVIDEDROLE,
	ASSEMBLYCONTEXT, ASSEMBLYCONNECTOR 
}
